### ISSUE TITLE
java.lang.IllegalStateException: Unsupported option number 21

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/koap#57]
```
Caused by java.lang.IllegalStateException: Unsupported option number 21
       at com.juul.koap.DecoderKt.readOption(DecoderKt.java:412)
       at com.juul.koap.DecoderKt.readOptions(DecoderKt.java:329)
       at com.juul.koap.DecoderKt.decodeContent(DecoderKt.java:194)
       at com.juul.koap.DecoderKt.decode(DecoderKt.java:178)
       at com.juul.koap.DecoderKt.decode$default(DecoderKt.java:175)
       <redacted>
       at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(FlowKt__TransformKt.java:137)
       at com.juul.kable.Observers$acquire$$inlined$map$1$2.emit(Observers.java:137)
       at com.juul.kable.Observers$acquire$$inlined$filter$1$2.emit(Observers.java:137)
       at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(SubscribedFlowCollector.java:2)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlowImpl.java:351)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlowImpl.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by twyatt** [comment]
After further investigation, it seems likely that the peripheral being communicated with is sending an invalid/corrupt CoAP message.
